scaffold-eth/punk-wallet

- packages/react-app/src/App.jsx
> Make the network selector tall enough to show all the options without the scrollbar

- packages/react-app/src/App.jsx
- packages/react-app/src/components/WalletConnectTransactionDisplay.jsx
> Simulate Wallet Connect transactions on Tenderly

- packages/react-app/src/components/WalletConnectTransactionDisplay.jsx
I've just realised that we only want to simulate transactions, not e.g. a personal sign, because it won't work.
> We don't want to simuate 'eth_sign', 'personal_sign' and 'eth_signTypedData'

- packages/react-app/src/App.jsx
Fix is to ask rpc for gas price on goerli network
> Fix incorrect gas price estimation on goerli

- packages/react-app/src/App.jsx
- packages/react-app/src/components/EtherInput.jsx
Added a mx button to the ether input component
> Created a max button

- packages/react-app/package.json
- packages/react-app/src/App.jsx
- packages/react-app/src/components/IFrame.jsx
- packages/react-app/src/components/index.js
- packages/react-app/src/contexts/SafeInjectContext.tsx
- packages/react-app/src/helpers/communicator.ts
- packages/react-app/src/helpers/messageFormatter.ts
- packages/react-app/src/helpers/types.ts
- packages/react-app/src/helpers/utils.ts
- packages/react-app/src/index.jsx
- packages/react-app/src/react-app-env.d.ts
- packages/react-app/tsconfig.json
- yarn.lock
> Add support to connect dapp via iframe

- packages/react-app/src/App.jsx
- packages/react-app/src/components/IFrame.jsx
Fixed bug that was causing a WSOD:
Also added some tweaks so the iframe / load input looks better on mobile.
Before:
After:
> Fix WSOD (wrong default target network) + iframe better display on mobile

- packages/react-app/src/App.jsx
This PR is about the Dapp's image which is not aligned properly, when we use Wallet Connect.
**Currently:**
**Fixed:**
Cheers,
Tamas
> Position Dapp's image properly - using flex instead of calculating the offsets manually

- packages/react-app/src/constants.js
according to https://era.zksync.io/docs/dev/troubleshooting/important-links.html
> Update zkSync Era and Testnet 

- packages/react-app/src/components/WalletConnectTransactionPopUp.jsx
- packages/react-app/src/helpers/WalletConnectV2Helper.js
Speedrun demo:
https://deploy-preview-190--wonderful-kirch-4ab41a.netlify.app/
This PR:
https://cheerful-level.surge.sh/
> Use ethers to sign messages

- packages/react-app/src/App.jsx
- packages/react-app/src/components/IFrame.jsx
- packages/react-app/src/components/Monerium.jsx
> Move Monerium login button to the bottom

- packages/react-app/src/components/Monerium.jsx
This is a small fix to indicate that Monerium connection was successful.
> "Login with Monerium" / "Monerium Connected"

- packages/react-app/src/App.jsx
- packages/react-app/src/components/TransactionDisplay.jsx
- packages/react-app/src/helpers/MoneriumHelper.js
This PR is about refreshing the order state automatically (no need for page refresh), transition from "In Progress" to "Completed" should be around 10 sec.
> Refresh orders when there is a pending one

- packages/react-app/src/App.jsx
- packages/react-app/src/constants.js
- packages/react-app/src/hooks/UserProvider.js
> Mainnet RPC and Scroll

- packages/react-app/src/App.jsx
- packages/react-app/src/components/ERC20Input.jsx
- packages/react-app/src/components/ERC20Selector.jsx
- packages/react-app/src/components/MoneriumIban.jsx
- packages/react-app/src/components/SettingsModal.jsx
- packages/react-app/src/components/TokenDisplay.jsx
- packages/react-app/src/components/TransactionDisplay.jsx
- packages/react-app/src/components/TransactionResponseDisplay.jsx
- packages/react-app/src/components/index.js
- packages/react-app/src/helpers/SettingsHelper.js
- packages/react-app/src/helpers/TokenSettingsHelper.js
**Create Token Settings options, where we can change the order and the displayed tokens.**
Future plans:
Apply the same to networks.
Create an import option for tokens/networks.
https://github.com/scaffold-eth/punk-wallet/assets/1397179/8ddc2d6c-4627-4f06-b15d-3f8efa68a86a
> Token Settings modal

- packages/react-app/src/App.jsx
- packages/react-app/src/components/NetworkDisplay.jsx
- packages/react-app/src/components/SelectorWithSettings.jsx
- packages/react-app/src/components/SettingsModal.jsx
- packages/react-app/src/components/index.js
- packages/react-app/src/helpers/NetworkSettingsHelper.js
- packages/react-app/src/helpers/SettingsHelper.js
https://github.com/scaffold-eth/punk-wallet/assets/1397179/c21fcc36-4d07-46f0-8211-43b0bb859daf
> Network settings

- packages/react-app/src/constants.js
- packages/react-app/src/helpers/ChainHelper.js
This PR adds USDC for Base.
Also I imported DAI, just to see if token import works properly.
49a917db0cb
> Base - USDC

- packages/react-app/src/App.css
- packages/react-app/src/App.jsx
- packages/react-app/src/components/NetworkDetailedDisplay.jsx
- packages/react-app/src/components/TokenDetailedDisplay.jsx
- packages/react-app/src/components/TokenDisplay.jsx
- packages/react-app/src/components/TransactionDisplay.jsx
Hey @austintgriffith ,
I'm forwarding this PR from https://github.com/moltam89/punk-wallet/pull/4.
@phipsae used [prettier](https://prettier.io/)  to make the code look better, and also created a link blue color variable, solving one of the ToDos I left in the codebase.
Cheers,
Tamas
> Prettier and global blue link

- packages/react-app/src/App.jsx
- packages/react-app/src/components/Reload.jsx
- packages/react-app/src/components/index.js
Hey guys,
I think the App.jsx file is way too long, so I deleted the unused comments and created a separate Reload component.
Hitting the Reload button should find a network with some balance.
**Note:**
Probably it would be nice to run this balance search for users who just arrived.
https://github.com/scaffold-eth/punk-wallet/assets/1397179/e9209c19-8a10-423c-bed9-05ec7c03e091
> Refactor app - delete unused comments and create separate Reload component

- packages/react-app/src/App.jsx
https://caring-attraction.surge.sh/
> Forcing white background for the QR code - Dark Reader issue

- packages/react-app/src/components/SelectorWithSettings.jsx
Forwarded from https://github.com/scaffold-eth/punk-wallet/pull/101.
> Enhance SelectorWithSettings component: add search functionality and adjust list height dynamically

- packages/react-app/src/constants.js
> Base Sepolia network
